eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: serviceHi
  cloud:
    config:
      label: master
      profile: dev
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
management:
  security:
    enabled: false
